# Generated by Django 5.0 on 2025-12-17 08:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('region', models.CharField(choices=[('INTERNATIONAL', 'International'), ('AMERICAN', 'American')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website_url', models.URLField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_frequency_hours', models.IntegerField(default=24)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='rankings_co_name_8e7d34_idx'), models.Index(fields=['country'], name='rankings_co_country_153d0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollegeRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('academic_reputation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('employer_reputation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('faculty_student_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('research_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('international_diversity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('teaching_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('student_satisfaction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ranking_year', models.IntegerField()),
                ('data_source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.college')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.rankingsource')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='CacheMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetch_time', models.DateTimeField(blank=True, null=True)),
                ('last_successful_fetch', models.DateTimeField(blank=True, null=True)),
                ('fetch_status', models.CharField(choices=[('SUCCESS', 'Successful'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('colleges_fetched', models.IntegerField(default=0)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rankings.rankingsource')),
            ],
        ),
        migrations.CreateModel(
            name='RankingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('RESEARCH', 'Research & Innovation'), ('EMPLOYMENT', 'Employment Outcomes'), ('STUDENT_LIFE', 'Student Life'), ('DIVERSITY', 'Diversity & Inclusion'), ('INTERNATIONAL', 'International Presence'), ('INFRASTRUCTURE', 'Infrastructure & Facilities'), ('AFFORDABILITY', 'Affordability')], max_length=20)),
                ('strength_level', models.CharField(choices=[('EXCEPTIONAL', 'Exceptional'), ('STRONG', 'Strong'), ('AVERAGE', 'Average'), ('WEAK', 'Weak')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True)),
                ('college_ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='rankings.collegeranking')),
            ],
            options={
                'unique_together': {('college_ranking', 'category_type')},
            },
        ),
        migrations.AddIndex(
            model_name='collegeranking',
            index=models.Index(fields=['college', 'source'], name='rankings_co_college_a1ca57_idx'),
        ),
        migrations.AddIndex(
            model_name='collegeranking',
            index=models.Index(fields=['ranking_year'], name='rankings_co_ranking_78aa4f_idx'),
        ),
        migrations.AddIndex(
            model_name='collegeranking',
            index=models.Index(fields=['rank'], name='rankings_co_rank_2e7d47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collegeranking',
            unique_together={('college', 'source', 'ranking_year')},
        ),
    ]
